#!/usr/bin/env python3
import sys
import queue
import threading
import io
import os
import numpy as np
import scipy.io.wavfile as wav
import sounddevice as sd
import speech_recognition as sr
from contextlib import contextmanager

# --- ROS 2 Imports ---
import rclpy
from rclpy.node import Node
from std_msgs.msg import String

# --- PyQt5 Imports ---
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QLabel, QTextEdit, QLineEdit
from PyQt5.QtCore import Qt, QTimer, pyqtSignal

# ==============================================================================
# GLOBAL CONFIGURATION
# ==============================================================================

SAMPLE_RATE = 16000
CHANNELS = 1

# ==============================================================================
# UTILITY FUNCTIONS
# ==============================================================================

@contextmanager
def ignore_stderr():
    """
    Context manager to suppress standard error output.
    
    Used primarily to silence ALSA/PortAudio warnings generated by sounddevice
    that are irrelevant to the application logic.
    """
    try:
        with open(os.devnull, 'w') as devnull:
            old_stderr = os.dup(sys.stderr.fileno())
            os.dup2(devnull.fileno(), sys.stderr.fileno())
            try:
                yield
            finally:
                os.dup2(old_stderr, sys.stderr.fileno())
    except Exception:
        yield

# ==============================================================================
# MAIN INTERFACE CLASS
# ==============================================================================

class InterfaceNode(Node, QWidget):
    """
    Main HMI (Human-Machine Interface) node combining ROS 2 and PyQt5.

    Handles:
    1. Audio recording (Push-to-Talk via Spacebar).
    2. Speech-to-Text conversion using Google Speech Recognition.
    3. Text-based command input.
    4. Visualization of robot feedback in a log format.
    """

    # --- THREAD SIGNAL ---
    # Defines a signal to safely update the GUI from the audio thread
    log_signal = pyqtSignal(str, str)

    def __init__(self):
        """Initializes the ROS 2 node, UI components, and audio processing tools."""
        Node.__init__(self, 'interfaz_hmi_rai')
        QWidget.__init__(self)

        # Connect the signal to the slot
        self.log_signal.connect(self.update_log_slot)
        
        # --- ROS 2 Communication ---
        self.pub_human = self.create_publisher(String, '/from_human', 10)
        self.sub_feedback = self.create_subscription(String, '/robot_feedback', self.feedback_callback, 10)
        
        # --- Audio State ---
        self.audio_queue = queue.Queue()
        self.is_recording = False
        self.recognizer = sr.Recognizer()
        self.stream = None

        # --- Timers ---
        # Debounce timer to prevent accidental double-clicks or rapid toggles
        self.stop_timer = QTimer()
        self.stop_timer.setSingleShot(True)
        self.stop_timer.setInterval(150)
        self.stop_timer.timeout.connect(self.real_stop_rec)

        # ROS Spin Timer (integrates ROS loop into Qt event loop)
        self.ros_timer = QTimer()
        self.ros_timer.timeout.connect(self.spin_ros)
        self.ros_timer.start(20)

        # --- UI Initialization ---
        self.init_ui()

    def init_ui(self):
        """Configures the graphical user interface layout and widgets."""
        self.setWindowTitle("VIRC - Voice & Text Interface")
        self.setGeometry(100, 100, 450, 600)
        layout = QVBoxLayout()
        
        # 1. Status Label (Push-to-Talk Indicator)
        self.label = QLabel("HOLD [SPACE] TO SPEAK")
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setStyleSheet("""
                                font-size: 14px; 
                                background: #333333; 
                                color: white; 
                                padding: 20px; 
                                border-radius: 10px;
                                font-weight: bold;
                                """)
        layout.addWidget(self.label)
        
        # 2. Feedback Log (Console)
        self.log = QTextEdit()
        self.log.setReadOnly(True)
        self.log.setFocusPolicy(Qt.NoFocus) # Prevents stealing focus from Spacebar
        self.log.setStyleSheet("""
                               background: #1e1e1e; 
                               color: #d4d4d4; 
                               font-family: 'Consolas', 'Monaco', monospace; 
                               border-radius: 5px;
                               padding: 10px;
                               font-size: 12px
                               """)
        layout.addWidget(self.log)

        # 3. Manual Text Input
        self.text_input = QLineEdit()
        self.text_input.setPlaceholderText("Type a command and press Enter...")
        self.text_input.setStyleSheet("""
                                      padding: 10px; 
                                      border-radius: 5px;
                                      """)
        self.text_input.returnPressed.connect(self.send_text_command)
        layout.addWidget(self.text_input)
        
        self.setFocusPolicy(Qt.StrongFocus)
        self.setLayout(layout)
        
        # Critical: Force focus on main window to enable Spacebar PTT immediately
        self.setFocus()

    def spin_ros(self):
        """Executes a single step of the ROS 2 event loop."""
        rclpy.spin_once(self, timeout_sec=0)

    # ==========================================================================
    # LOGIC: FEEDBACK & TEXT
    # ==========================================================================

    def feedback_callback(self, msg):
        """
        Callback for robot feedback messages.
        
        Args:
            msg (std_msgs.msg.String): The message from the robot.
        """
        self.add_log(f"[AI]: {msg.data}", "#4FC3F7")

    def send_text_command(self):
        """
        Publishes text from the input field to the robot and resets focus.
        """
        text = self.text_input.text().strip()
        if text:
            self.add_log(f"[USER - TEXT]: {text}", "#8BC34A")
            
            msg = String()
            msg.data = text.lower()
            self.pub_human.publish(msg)
            
            self.text_input.clear()
            
            # Critical: Return focus to the main window so Spacebar works again
            self.setFocus() 

    # --- THREAD-SAFE LOGGING SYSTEM ---
    
    def add_log(self, text, color="#d4d4d4"):
        """
        Public function to request a log update. Safe to call from any thread.
        Emits a signal instead of touching the GUI directly.
        """
        self.log_signal.emit(text, color)

    def update_log_slot(self, text, color):
        """
        Slot that receives the signal. 
        Executes in the Main GUI Thread to update the widget safely.
        """
        html = f"<div style='color: {color}; margin-bottom: 5px;'>{text}</div>"
        self.log.append(html)

    # ==========================================================================
    # LOGIC: KEYBOARD EVENTS
    # ==========================================================================

    def keyPressEvent(self, event):
        """
        Handles key press events (Push-to-Talk logic).
        
        Args:
            event (QKeyEvent): The key event.
        """
        # If user is typing in the text box, ignore Spacebar PTT
        if self.text_input.hasFocus():
            super().keyPressEvent(event)
            return
        
        if event.key() == Qt.Key_Space:
            if not event.isAutoRepeat(): 
                if self.stop_timer.isActive():
                    self.stop_timer.stop()
                if not self.is_recording:
                    self.start_rec()

    def keyReleaseEvent(self, event):
        """
        Handles key release events to stop recording.
        
        Args:
            event (QKeyEvent): The key event.
        """
        if event.key() == Qt.Key_Space and not self.text_input.hasFocus():
             if not event.isAutoRepeat() and self.is_recording:
                self.stop_timer.start()

    # ==========================================================================
    # LOGIC: AUDIO PROCESSING
    # ==========================================================================

    def audio_callback(self, indata, frames, time, status):
        """
        Callback for sounddevice input stream. Puts raw data into the queue.
        """
        if self.is_recording:
            self.audio_queue.put(indata.copy())

    def start_rec(self):
        """Initializes audio stream and updates UI."""
        self.is_recording = True
        self.audio_queue.queue.clear()
        self.label.setText("[RECORDING IN PROGRESS...]")
        self.label.setStyleSheet("""
                                font-size: 14px; 
                                background: #4CAF50; 
                                color: white; 
                                padding: 20px; 
                                border-radius: 10px;
                                font-weight: bold;
                                """)
        
        try:
            with ignore_stderr():
                self.stream = sd.InputStream(samplerate=SAMPLE_RATE, channels=CHANNELS, callback=self.audio_callback)
                self.stream.start()
        except Exception as e:
            self.add_log(f"[HARDWARE ERROR] Microphone: {e}", "red")
            self.is_recording = False
            self.reset_ui()

    def real_stop_rec(self):
        """Stops the audio stream and triggers background processing."""
        if not self.is_recording: return
        self.is_recording = False
        
        try:
            if self.stream:
                self.stream.stop()
                self.stream.close()
        except Exception: 
            pass
        
        self.label.setText("[PROCESSING AUDIO...]")
        self.label.setStyleSheet("""
                                font-size: 14px; 
                                background: #FFC107; 
                                color: black; 
                                padding: 20px; 
                                border-radius: 10px;
                                font-weight: bold;
                                """)
        
        threading.Thread(target=self.process_audio).start()

    def process_audio(self):
        """
        Consolidates audio buffer and performs Speech-to-Text via Google API.
        Runs in a separate thread to prevent UI freezing.
        """
        try:
            data = []
            while not self.audio_queue.empty():
                data.append(self.audio_queue.get())
            
            # 1. Empty buffer check
            if not data:
                self.add_log("[WARNING] Audio input empty.", "orange")
                return

            full_audio = np.concatenate(data, axis=0)
            
            # 2. Time-based filter (0.2 seconds threshold)
            # Prevents accidental short clicks from triggering the API
            duration_seconds = len(full_audio) / SAMPLE_RATE
            if duration_seconds < 0.2:
                self.add_log(f"[WARNING] Input too short ({duration_seconds:.2f}s). Ignored.", "orange")
                return 

            # Convert to int16
            audio_int16 = (full_audio * 32767).astype(np.int16)
            
            f = io.BytesIO()
            wav.write(f, SAMPLE_RATE, audio_int16)
            f.seek(0)

            with sr.AudioFile(f) as source:
                audio = self.recognizer.record(source)
            
            # 3. Speech Recognition
            # If audio is silence, this throws UnknownValueError
            text = self.recognizer.recognize_google(audio, language="es-ES")
            
            self.add_log(f"[USER - VOICE]: {text}", "#8BC34A")
            
            msg = String()
            msg.data = text.lower()
            self.pub_human.publish(msg)
            
        except sr.UnknownValueError:
            self.add_log("[WARNING] No speech detected (Silence/Unintelligible).", "orange")
            
        except sr.RequestError as e:
            self.add_log(f"[ERROR] Google API: {e}", "red")
        except Exception as e:
            self.add_log(f"[ERROR] Internal: {str(e)}", "red")
        finally:
            QTimer.singleShot(0, self.reset_ui)

    def reset_ui(self):
        """Resets the UI to the idle state."""
        self.label.setText("HOLD [SPACE] TO SPEAK")
        self.label.setStyleSheet("""
                                font-size: 14px; 
                                background: #333333; 
                                color: white; 
                                padding: 20px; 
                                border-radius: 10px;
                                font-weight: bold;
                                """)

# ==============================================================================
# ENTRY POINT
# ==============================================================================

def main():
    rclpy.init()
    app = QApplication(sys.argv)
    node = InterfaceNode()
    node.show()
    try:
        sys.exit(app.exec_())
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == "__main__":
    main()